# Generated by Django 4.2 on 2024-08-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='dating_images')),
                ('text_status', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Dating',
                'verbose_name_plural': 'Dating',
            },
        ),
    ]
