# Generated by Django 4.2 on 2024-08-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0002_dating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dating',
            options={'ordering': ['text_status'], 'verbose_name': 'Dating', 'verbose_name_plural': 'Dating'},
        ),
    ]
