# Generated by Django 4.2 on 2024-08-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0003_alter_dating_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dating',
            options={'ordering': ['-text_status'], 'verbose_name': 'Dating', 'verbose_name_plural': 'Dating'},
        ),
    ]
