# Generated by Django 4.2 on 2024-08-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0004_alter_dating_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_to', models.BigIntegerField(default=0)),
                ('data_speed', models.BigIntegerField(default=0)),
                ('number', models.BigIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'OnlineMembers',
                'verbose_name_plural': 'OnlineMembers',
                'ordering': ['-data_to'],
            },
        ),
    ]
