# Generated by Django 4.2 on 2024-08-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0007_alter_onlinemembers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinemembers',
            options={'ordering': ['id'], 'verbose_name': 'OnlineMembers', 'verbose_name_plural': 'OnlineMembers'},
        ),
        migrations.AlterField(
            model_name='onlinemembers',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
