# Generated by Django 4.2 on 2024-08-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0008_alter_onlinemembers_options_alter_onlinemembers_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinemembers',
            options={'ordering': ['-id'], 'verbose_name': 'OnlineMembers', 'verbose_name_plural': 'OnlineMembers'},
        ),
    ]
