# Generated by Django 4.2 on 2024-08-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0011_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
