# Generated by Django 4.2 on 2024-08-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0012_profile_is_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_live',
        ),
    ]
