# Generated by Django 4.2 on 2024-09-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0018_likenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='likenotification',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
