# Generated by Django 4.2 on 2024-09-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0019_likenotification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likenotification',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='likenotification',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
