# Generated by Django 4.2 on 2024-09-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0020_remove_likenotification_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likenotification',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
