# Generated by Django 4.2 on 2024-09-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0021_alter_likenotification_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likenotification',
            name='date',
        ),
        migrations.AddField(
            model_name='likenotification',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
