# Generated by Django 4.2 on 2024-09-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0022_remove_likenotification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
