# Generated by Django 4.2 on 2024-10-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0024_likenotification_closed_by_liked_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Contact',
                'ordering': ['id'],
            },
        ),
    ]
