# Generated by Django 4.2 on 2024-10-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0025_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveuser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveuser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
