# Generated by Django 4.2 on 2024-11-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0027_remove_profile_height_remove_profile_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
