# Generated by Django 4.2 on 2025-01-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0028_profile_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveuser',
            name='is_live',
        ),
        migrations.AddField(
            model_name='liveuser',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
