# Generated by Django 4.2 on 2025-01-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0029_remove_liveuser_is_live_liveuser_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
